### ISSUE TITLE
LAUNCH_ENVIRONMENTS: cannot accept values with spaces

### ISSUE THREAD

**Issue by winklevos** [ix-ai/swarm-launcher#20]
`'OPENVPN_VERBOSITY=1 TZ=xx/xx REGION=US Chicago'`

Will result in:
```
REGION: US
Chicago: null
```

`"OPENVPN_VERBOSITY=1 TZ=xx/xx "REGION=US Chicago"`
results in 
`REGION: US - Chicago`

escaping  with `\` or quoting `"US Chicago"` has not worked

**Comment by tlex** [comment]
Unfortunately, this can't be fixed without breaking existing configurations. I'm looking at two different solutions:
* replace a string (like `@_@`) with a single space in `LAUNCH_ENVIRONMENTS`
* add `LAUNCH_ENVIRONMENTS_COMMA` where the separator between the various environment keys is a comma, instead of whitespace

**Comment by tlex** [comment]
https://github.com/ix-ai/swarm-launcher/commit/f3ff79b32b5237a4f43ff4eafaac768ccefc1dab

**Comment by tlex** [comment]
I've released [v0.7.1](https://github.com/ix-ai/swarm-launcher/releases/tag/v0.7.1). Please give it a spin and see if using `@_@' instead of space solves your problem.

**Comment by winklevos** [comment]
Thanks @tlex i've give it a shot, the comma idea has similar issues are in my string i have "=10.0.0.0/16,192.168.0.0.24"

Ideally it would be consider quotations in the string so "REGION=\"US Chicago\"" or similar. I'll get back to you shortly if it is functioning as expected, many thanks!
